//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace New_Cycle_2._0
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Formu_calidad
    {
        public int FormularioID { get; set; }
        public string Observaciones { get; set; }
        [DisplayName("Aspectos a mejorar")]
        public string Aspectos_a_mejorar { get; set; }
        [DisplayName("Ruta")]
        public int RutaID { get; set; }
    
        public virtual Ruta Ruta { get; set; }
    }
}
