//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace New_Cycle_2._0
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Intercambio
    {
        public int IntercambioID { get; set; }
        [Required(ErrorMessage = "Campo requerido.")]
        [DisplayName("Empresa asociada")]
        public int EmpresaID { get; set; }
        [Required(ErrorMessage = "Campo requerido.")]
        [DisplayName("Producto a entregar")]
        public int ProductoAInterID { get; set; }
        [Required(ErrorMessage = "Campo requerido.")]
        [DisplayName("Producto a recibir")]
        public int ProductoInterID { get; set; }
        [Required(ErrorMessage = "Campo requerido.")]
        [DisplayName("Descripcion del intercambio")]
        public string Descripcion_del_intercambio { get; set; }
    
        public virtual Empresas Empresas { get; set; }
        public virtual Producto_a_intercambiar Producto_a_intercambiar { get; set; }
        public virtual Producto_intercambiado Producto_intercambiado { get; set; }
    }
}
