//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace New_Cycle_2._0
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class New_cycle_Com_RecoEntities : DbContext
    {
        public New_cycle_Com_RecoEntities()
            : base("name=New_cycle_Com_RecoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Compras> Compras { get; set; }
        public virtual DbSet<Formu_calidad> Formu_calidad { get; set; }
        public virtual DbSet<Metodos_de_pago> Metodos_de_pago { get; set; }
        public virtual DbSet<Productos> Productos { get; set; }
        public virtual DbSet<PuntoEntrega> PuntoEntrega { get; set; }
        public virtual DbSet<Ruta> Ruta { get; set; }
    }
}
