//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace New_Cycle_2._0
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class New_CycleEntities : DbContext
    {
        public New_CycleEntities()
            : base("name=New_CycleEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Clientes> Clientes { get; set; }
        public virtual DbSet<Colaboradores> Colaboradores { get; set; }
        public virtual DbSet<Empresas> Empresas { get; set; }
        public virtual DbSet<Intercambio> Intercambio { get; set; }
        public virtual DbSet<Producto_a_intercambiar> Producto_a_intercambiar { get; set; }
        public virtual DbSet<Producto_intercambiado> Producto_intercambiado { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
    }
}
