//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace New_Cycle_2._0
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Xml.Linq;

    public partial class Usuarios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuarios()
        {
            this.Clientes = new HashSet<Clientes>();
            this.Colaboradores = new HashSet<Colaboradores>();
            this.Empresas = new HashSet<Empresas>();
        }
    
        public int UsuarioID { get; set; }

        [Required(ErrorMessage = "Campo requerido.")]
        [DisplayName("Nombre y Apellidos O Nombre de Empresa")]
        public string Nombre { get; set; }

        [EmailAddress(ErrorMessage = "Ingresa una dirección de correo electrónico válida.")]
        [Required(ErrorMessage = "Campo requerido.")]
        public string Email { get; set; }
        [Required(ErrorMessage = "Campo requerido.")]
        public string Telefono { get; set; }
        [DataType(DataType.Password)]
        [Required(ErrorMessage = "Campo requerido.")]
        public string Contraseña { get; set; }

        [Display(Name = "Confirmar Contraseña")]
        [DataType(DataType.Password)]
        [Required(ErrorMessage = "Campo requerido.")]
        public string ConfirmarContraseña { get; set; }
       
        [Required(ErrorMessage = "Campo requerido.")]
        [DisplayName("Tipo de Usuario")]
        public string Tipo_de_Usuario { get; set; }


        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Clientes> Clientes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Colaboradores> Colaboradores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Empresas> Empresas { get; set; }
    }
}
